"""create chat tables

Revision ID: bd6414eb2f9e
Revises: 
Create Date: 2026-07-28 11:18:51.772156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6414eb2f9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'health_risk_prediction' not in existing_tables:
        op.create_table('health_risk_prediction',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('diabetes_probability', sa.Float(), nullable=False),
        sa.Column('hypertension_probability', sa.Float(), nullable=False),
        sa.Column('model_version', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'health_chat_session' not in existing_tables:
        op.create_table('health_chat_session',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('health_risk_prediction_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['health_risk_prediction_id'], ['health_risk_prediction.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'health_chat_message' not in existing_tables:
        op.create_table('health_chat_message',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=10), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['health_chat_session.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    existing_columns = [col['name'] for col in inspector.get_columns('user_health_profile')]
    if 'height_cm' not in existing_columns:
        op.add_column('user_health_profile', sa.Column('height_cm', sa.Float(), nullable=False, server_default='0'))
    if 'weight_kg' not in existing_columns:
        op.add_column('user_health_profile', sa.Column('weight_kg', sa.Float(), nullable=False, server_default='0'))
    if 'weight' in existing_columns:
        op.drop_column('user_health_profile', 'weight')
    if 'height' in existing_columns:
        op.drop_column('user_health_profile', 'height')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_health_profile', sa.Column('height', sa.FLOAT(), nullable=False, server_default='0'))
    op.add_column('user_health_profile', sa.Column('weight', sa.FLOAT(), nullable=False, server_default='0'))
    op.drop_column('user_health_profile', 'weight_kg')
    op.drop_column('user_health_profile', 'height_cm')
    op.drop_table('health_chat_message')
    op.drop_table('health_chat_session')
    op.drop_table('health_risk_prediction')
    # ### end Alembic commands ###
